return {
    ALL_MODEL_TYPES = {
        "Eye", "Feet", "Hands", "Head", "Lower Arms", "Lower Legs", "Misc",
        "Torso", "Upper Arms", "Upper Legs", "Universal"
    },
    ALL_SHOP_TYPES = {
        "Eye", "Feet", "Hands", "Head", "Lower Arms", "Lower Legs", "Misc",
        "Torso", "Upper Arms", "Upper Legs", "Ears"
    },
    ALL_CATEGORIES = {
        "Accessories", "Ears", "Eyes", "Heads", "LeftFeet", "LeftHands",
        "LowerLeftArms", "LowerLeftLegs", "LowerRightArms", "LowerRightLegs",
        "RightFeet", "RightHands", "Torsos", "UpperLeftArms", "UpperLeftLegs",
        "UpperRightArms", "UpperRightLegs"
    }
}